if(NOT DEFINED TOOL OR NOT DEFINED EXPECTED OR EXPECTED STREQUAL "")
  message(FATAL_ERROR "expect_failure requires TOOL and a nonempty EXPECTED diagnostic")
endif()
execute_process(COMMAND "${TOOL}" ${ARGS}
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result MATCHES "^[1-9][0-9]*$")
  message(FATAL_ERROR "Expected a normal nonzero exit, got '${result}':\n${output}\n${error}")
endif()
string(FIND "${output}\n${error}" "${EXPECTED}" found)
if(found EQUAL -1)
  message(FATAL_ERROR "Exit ${result} lacked expected diagnostic '${EXPECTED}':\n${output}\n${error}")
endif()
