file(MAKE_DIRECTORY "${WORK}")
execute_process(COMMAND "${TOOL}" -mode tune -write_config "${WORK}/tune.json" RESULT_VARIABLE rc OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "tune defaults: ${output}\n${error}")
endif()
file(READ "${WORK}/tune.json" defaults)
foreach(key filter write_rt write_im write_intensity)
  string(JSON value GET "${defaults}" "${key}")
  if(value)
    message(FATAL_ERROR "tune mode enabled ${key}")
  endif()
endforeach()
file(WRITE "${WORK}/override.json" "{\"q_precursor\":0.5}\n")
execute_process(COMMAND "${TOOL}" -mode refine -config "${WORK}/override.json" -q_precursor 0.002 -write_config "${WORK}/effective.json" RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "explicit TOPP option did not override JSON")
endif()
file(READ "${WORK}/effective.json" effective)
string(JSON q GET "${effective}" q_precursor)
if(NOT q STREQUAL "0.002")
  message(FATAL_ERROR "expected q_precursor 0.002, got ${q}")
endif()
foreach(case filter write_rt write_im write_intensity)
  file(WRITE "${WORK}/conflict.json" "{\"${case}\":true}\n")
  execute_process(COMMAND "${TOOL}" -mode tune -config "${WORK}/conflict.json" -write_config "${WORK}/invalid.json" RESULT_VARIABLE rc OUTPUT_QUIET ERROR_QUIET)
  if(rc EQUAL 0)
    message(FATAL_ERROR "tune mode accepted ${case}=true")
  endif()
endforeach()
file(WRITE "${WORK}/minmax.json" "{\"rt_unit\":\"minmax\"}\n")
execute_process(COMMAND "${TOOL}" -mode refine -tune -config "${WORK}/minmax.json" -write_config "${WORK}/invalid.json" RESULT_VARIABLE rc OUTPUT_QUIET ERROR_QUIET)
if(rc EQUAL 0)
  message(FATAL_ERROR "tuning accepted minmax through JSON")
endif()
file(WRITE "${WORK}/negative.json" "{\"min_fragments\":-1}\n")
execute_process(COMMAND "${TOOL}" -mode refine -config "${WORK}/negative.json" -write_config "${WORK}/invalid.json" RESULT_VARIABLE rc OUTPUT_QUIET ERROR_QUIET)
if(rc EQUAL 0)
  message(FATAL_ERROR "negative fragment count became an unsigned count")
endif()
message(STATUS "refinement config contract passed")
