#!/usr/bin/env python3
"""Verify shipped x86_64/aarch64 AppImage helpers and collect pinned source notices."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import struct
import subprocess
import tarfile
import urllib.request


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def fetch(url, destination, expected):
    if not destination.exists():
        destination.parent.mkdir(parents=True, exist_ok=True)
        try:
            with urllib.request.urlopen(url, timeout=120) as source, destination.open('wb') as output:
                shutil.copyfileobj(source, output)
        except Exception:
            destination.unlink(missing_ok=True)
            raise
    if sha256(destination.read_bytes()) != expected:
        raise RuntimeError(f'unrecognized AppImage source/runtime bytes: {url}')
    return destination


def verify_runtime(actual, reference, pin):
    if len(actual) != pin['size'] or sha256(reference) != pin['sha256']:
        raise RuntimeError('AppImage runtime size or reference hash changed; review its corresponding sources')
    # appimagetool fills these data sections with this image's checksum, update
    # information or signature. All executable code and ELF metadata must match.
    normalized = bytearray(actual)
    for section in pin['mutable_sections']:
        start, size = section['offset'], section['size']
        if reference[start:start + size] != bytes(size):
            raise RuntimeError('runtime mutable-section pin does not match the reference')
        normalized[start:start + size] = bytes(size)
    if normalized != reference:
        raise RuntimeError('unrecognized AppImage runtime; update pins only after reviewing its sources')
    version = 'https://github.com/AppImage/type2-runtime/commit/' + pin['revision'][:7]
    if version.encode() not in actual:
        raise RuntimeError('runtime source revision is absent from its binary')
    return {'size': len(actual), 'sha256': sha256(actual), 'version': version}


def original_notices(archive, destination, name):
    notices = []
    with tarfile.open(archive) as source:
        for member in source:
            path = Path(member.name)
            if not member.isfile() or len(path.parts) != 2:
                continue
            if not re.fullmatch(r'(LICENSE|COPYING|COPYRIGHT|NOTICE|[AL]?GPL\d*)([._-].*)?', path.name, re.I):
                continue
            output = destination / (name + '-' + path.name)
            output.parent.mkdir(parents=True, exist_ok=True)
            with source.extractfile(member) as content, output.open('wb') as stream:
                shutil.copyfileobj(content, stream)
            notices.append(str(output.resolve()))
        if name == 'appimagekit':
            member = next(m for m in source.getmembers() if m.name.endswith('/src/AppRun.c'))
            text = source.extractfile(member).read().decode().split('*/', 1)[0] + '*/\n'
            output = destination / 'AppRun-COPYRIGHT.txt'
            output.write_text(text)
            notices.append(str(output.resolve()))
    if not notices and name != 'alpine-aports':
        raise RuntimeError(f'no original license notices found in {archive}')
    return notices


def verify_gtk_hook(actual, source):
    prefix = source.split('cat > "$HOOKFILE" <<\\EOF\n', 1)[1].split('\nEOF', 1)[0] + '\n'
    if not actual.startswith(prefix):
        raise RuntimeError('GTK hook differs from its pinned source template')
    expected = {'GSETTINGS_SCHEMA_DIR', 'GI_TYPELIB_PATH', 'GTK_EXE_PREFIX', 'GTK_PATH',
                'GTK_IM_MODULE_FILE', 'GDK_PIXBUF_MODULE_FILE', 'GIO_EXTRA_MODULES'}
    found = []
    for line in actual[len(prefix):].splitlines():
        match = re.fullmatch(r'export ([A-Z_]+)="\$APPDIR/([A-Za-z0-9_./+-]+)"', line)
        if not match or '..' in Path(match[2]).parts:
            raise RuntimeError('GTK hook contains an unknown generated statement')
        found.append(match[1])
    if len(found) != len(expected) or set(found) != expected:
        raise RuntimeError('GTK hook generated paths differ from the pinned GTK3 recipe')


def verify_wrapper(actual, hooks):
    prefix = ('#! /usr/bin/env bash\n\n# autogenerated by linuxdeploy\n\n'
              '# make sure errors in sourced scripts will cause this script to stop\nset -e\n\n'
              'this_dir="$(readlink -f "$(dirname "$0")")"\n\n')
    suffix = '\nexec "$this_dir"/AppRun.wrapped "$@"\n'
    if not actual.startswith(prefix) or not actual.endswith(suffix):
        raise RuntimeError('AppRun wrapper differs from its pinned linuxdeploy template')
    names = []
    for line in actual[len(prefix):-len(suffix)].splitlines():
        match = re.fullmatch(r'source "\$this_dir"/apprun-hooks/(?:"([\w.-]+)"|([\w.-]+))', line)
        if not match:
            raise RuntimeError('AppRun wrapper contains an unknown generated statement')
        names.append(match[1] or match[2])
    if len(names) != len(hooks) or set(names) != set(hooks):
        raise RuntimeError('AppRun wrapper hooks differ from the attributed payload')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--appimage', type=Path, required=True)
    parser.add_argument('--appdir', type=Path, required=True)
    parser.add_argument('--tools', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    here = Path(__file__).resolve().parent
    pins = json.loads((here / 'appimage-helper-pins.json').read_text())
    locked = json.loads((here.parent / 'gui/package-lock.json').read_text())
    if locked['packages']['node_modules/@tauri-apps/cli']['version'] != pins['tauri_cli']['version']:
        raise RuntimeError('Tauri CLI changed; recheck its helper downloads')
    if not args.appdir.is_dir():
        raise RuntimeError('the AppDir to inventory is absent')
    with args.appimage.open('rb') as stream:
        header = stream.read(20)
    if header[:6] != b'\x7fELF\x02\x01':
        raise RuntimeError('expected a 64-bit little-endian AppImage')
    machine = struct.unpack_from('<H', header, 18)[0]
    arches = [name for name, pin in pins['architectures'].items() if pin['elf_machine'] == machine]
    if len(arches) != 1:
        raise RuntimeError('AppImage architecture lacks reviewed helper provenance')
    arch = arches[0]
    cache = args.tools / 'dialibgen-provenance' / pins['runtime']['revision']
    runtime = {**pins['runtime'], **pins['architectures'][arch]['runtime']}
    reference = fetch(runtime['url'], cache / ('runtime-' + arch), runtime['sha256']).read_bytes()
    offset = int(subprocess.check_output([str(args.appimage.resolve()), '--appimage-offset'], text=True, timeout=30))
    with args.appimage.open('rb') as stream:
        actual = stream.read(offset)
        if stream.read(4) != b'hsqs':
            raise RuntimeError('AppImage runtime offset does not point to its SquashFS payload')
    evidence = verify_runtime(actual, reference, runtime)
    records, notices = {}, {}
    for record in pins['sources']:
        archive = fetch(record['url'], cache / record['filename'], record['sha256'])
        records[record['name']] = record
        notices[record['name']] = original_notices(archive, cache / 'notices', record['name'])
    helper = {**pins['apprun'], **pins['architectures'][arch]['apprun']}
    runtime_sources = {'type2-runtime', 'libfuse', 'squashfuse', 'musl', 'zstd', 'zlib', 'mimalloc', 'alpine-aports'}
    providers = [
        {'name': 'AppRun', 'license': 'MIT', 'source_revision': helper['revision'],
         'sha256': [helper['sha256']], 'build_ids': [helper['build_id']],
         'notices': notices['appimagekit'], 'sources': [records['appimagekit']]},
        {'name': 'AppImage-type2-runtime', 'license': 'MIT AND LGPL-2.1-only AND BSD-2-Clause AND BSD-3-Clause AND Zlib',
         'source_revision': runtime['revision'], 'appimage_runtime': evidence,
         'upstream_runtime_sha256': runtime['sha256'], 'build_log': runtime['build_log'],
         'static_dependencies': runtime['static_dependencies'], 'alpine_image': runtime['alpine_image'],
         'notices': [p for name, paths in notices.items() if name in runtime_sources for p in paths]
                    + [str(here / 'appimage-runtime-rebuild.md'), str(here / 'appimage-helper-pins.json')],
         'sources': [record for name, record in records.items() if name in runtime_sources]},
    ]
    hook = args.appdir / 'apprun-hooks/linuxdeploy-plugin-gtk.sh'
    if hook.is_file():
        with tarfile.open(cache / records['linuxdeploy-gtk']['filename']) as source:
            member = next(m for m in source if m.name.endswith('/linuxdeploy-plugin-gtk.sh'))
            verify_gtk_hook(hook.read_text(), source.extractfile(member).read().decode())
        providers.append({'name': 'linuxdeploy-gtk-hook', 'license': 'MIT', 'sha256': [sha256(hook.read_bytes())],
                          'source_revision': records['linuxdeploy-gtk']['revision'],
                          'notices': notices['linuxdeploy-gtk'], 'sources': [records['linuxdeploy-gtk']]})
    wrapper = args.appdir / 'AppRun'
    if wrapper.read_bytes().startswith(b'#!'):
        verify_wrapper(wrapper.read_text(), [p.name for p in (args.appdir / 'apprun-hooks').iterdir() if p.is_file()])
        providers.append({'name': 'linuxdeploy-AppRun-wrapper', 'license': 'MIT', 'sha256': [sha256(wrapper.read_bytes())],
                          'source_revision': records['linuxdeploy-wrapper']['revision'],
                          'notices': notices['linuxdeploy-wrapper'], 'sources': [records['linuxdeploy-wrapper']]})
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(providers, indent=2) + '\n')
    print('Verified AppImage runtime bytes and archived-source notice pins for AppRun and all static runtime libraries')


if __name__ == '__main__':
    main()
