#!/usr/bin/env python3
"""Offline refusal tests for executable-code and generated-hook attribution."""
import importlib.util
from pathlib import Path

spec = importlib.util.spec_from_file_location('helpers', Path(__file__).with_name('appimage-helper-providers.py'))
helpers = importlib.util.module_from_spec(spec)
spec.loader.exec_module(helpers)


def refused(call):
    try:
        call()
    except RuntimeError:
        return
    raise AssertionError('unattributed executable content was accepted')


reference = b'https://github.com/AppImage/type2-runtime/commit/1234567\0' + bytes(16)
pin = {'size': len(reference), 'sha256': helpers.sha256(reference), 'revision': '1234567' + '0' * 33,
       'mutable_sections': [{'offset': len(reference) - 16, 'size': 16}]}
assert helpers.verify_runtime(reference, reference, pin)['sha256'] == pin['sha256']
updated = reference[:-16] + b'x' * 16
assert helpers.verify_runtime(updated, reference, pin)['sha256'] != pin['sha256']
refused(lambda: helpers.verify_runtime(b'X' + reference[1:], reference, pin))
refused(lambda: helpers.verify_runtime(reference[:-1], reference, pin))
refused(lambda: helpers.verify_runtime(reference, b'X' + reference[1:], pin))

prefix = '#! /usr/bin/env bash\nexport TEST=value\n'
source = 'cat > "$HOOKFILE" <<\\EOF\n' + prefix + 'EOF\n'
keys = ['GSETTINGS_SCHEMA_DIR', 'GI_TYPELIB_PATH', 'GTK_EXE_PREFIX', 'GTK_PATH',
        'GTK_IM_MODULE_FILE', 'GDK_PIXBUF_MODULE_FILE', 'GIO_EXTRA_MODULES']
hook = prefix + ''.join(f'export {key}="$APPDIR/usr/lib/example"\n' for key in keys)
helpers.verify_gtk_hook(hook, source)
refused(lambda: helpers.verify_gtk_hook(hook + 'touch /tmp/not-allowed\n', source))
refused(lambda: helpers.verify_gtk_hook(hook.replace('/usr/lib/example', '/$(id)'), source))
refused(lambda: helpers.verify_gtk_hook(hook.replace('/usr/lib/example', '/../outside'), source))
refused(lambda: helpers.verify_gtk_hook(hook.replace('export GTK_PATH', 'export GTK_EXE_PREFIX'), source))

wrapper = ('#! /usr/bin/env bash\n\n# autogenerated by linuxdeploy\n\n'
           '# make sure errors in sourced scripts will cause this script to stop\nset -e\n\n'
           'this_dir="$(readlink -f "$(dirname "$0")")"\n\n'
           'source "$this_dir"/apprun-hooks/"gtk.sh"\n\nexec "$this_dir"/AppRun.wrapped "$@"\n')
helpers.verify_wrapper(wrapper, ['gtk.sh'])
refused(lambda: helpers.verify_wrapper(wrapper, ['unknown.sh']))
refused(lambda: helpers.verify_wrapper(wrapper.replace('set -e', 'set +e'), ['gtk.sh']))
refused(lambda: helpers.verify_wrapper(wrapper.replace('gtk.sh', '../gtk.sh'), ['gtk.sh']))
print('AppImage helper attribution: metadata-only changes accepted; executable changes, injected hooks and path escapes refused')
